#!/bin/sh 

# Wait for the property system to be up. 
while [ ! -e /dev/socket/property_service ]; do sleep 0.1; done 

# Enable WIFI 
while [ ! -e /dev/wcnss_wlan ]; do sleep 0.2; done 
echo 1 > /dev/wcnss_wlan

# Store updates on userdata partition since cache is too small
umount /android/cache || true
mkdir -p /userdata/cache
mount -o bind /userdata/cache /android/cache
